spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kioo/config-repo.git
          username: f2114198@163.com
          password: 5218791github
          basedir: C:\ideaworkspace\configgit
  rabbitmq:
    host: 192.168.88.134
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
